# You can generate your token from https://github.com/settings/tokens
# KEEP IT SECRET!
github-token = ""
# Managed repositories
repos = ["pingcap/tidb", "tikv/tikv", "pingcap/pd"]
# Release note repo
release-note-repo = "pingcap/release-note"
# Release note example, {repo} will be replaced by repo name
# eg. https://github.com/you06/release-note-poc
release-note-path = "/{product}"
# Default release note language pull request
pull-language = "en"

[[product]]
name = "tidb"
repos = ["pingcap/tidb", "tikv/tikv", "pingcap/pd", "pingcap/tics",
  "pingcap/br", "pingcap/dumpling", "pingcap/tidb-lightning", "pingcap/ticdc"]
rename = {"pingcap/tics" = "PingCAP/TiFlash", "pingcap/tidb" = "PingCAP/TiDB", "tikv/tikv" = "TiKV/TiKV", "pingcap/pd" = "PingCAP/PD", "pingcap/br" = "PingCAP/BR", "pingcap/dumpling" = "PingCAP/Dumpling", "pingcap/tidb-lightning" = "PingCAP/Lightning", "pingcap/ticdc" = "PingCAP/TiCDC"}
structure = [
  "pingcap/tidb",
  "tikv/tikv",
  "pingcap/pd",
  "pingcap/tics",
  "Tools: pingcap/br, pingcap/dumpling, pingcap/tidb-lightning, pingcap/ticdc"
]
label2type={"compatibility-breaker" = "Compatibility Changes", "type/bug-fix" = "Bug Fixes", "type/new-feature" = "New Features"}
