# You can generate your token from https://github.com/settings/tokens
# KEEP IT SECRET!
github-token = ""
# Managed repositories
repos = ["pingcap/tidb", "tikv/tikv", "pingcap/pd"]
# Release note repo
release-note-repo = "pingcap/release-note"
# Release note example, {repo} will be replaced by repo name
# eg. https://github.com/you06/release-note-poc
release-note-path = "/{product}"
# Default release note language pull request
pull-language = "en"

[[product]]
name = "tidb"
repos = ["pingcap/tidb", "tikv/tikv", "pingcap/pd", "pingcap/tics"]
rename = { "pingcap/tics" = "pingcap/tiflash" }
